### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DheerajP** [ozdemirburak/jquery-floating-social-share#10] opened 2016-11-16 14:29 UTC
@ozdemirburak 
No console errors. Nothing.
just not showing the share icons.

http://sitecoreblog.tools4geeks.com/

**Comment by ozdemirburak** [comment] 2016-11-18 02:26
You have a problem with your urchinTracker script, this is not a problem related to the plugin itself. 

Console shows it, `Uncaught SyntaxError: Unexpected token var`.

var _gat = {
    _getTrackerByName: function() {
        _trackEvent: function() {}
    }
};

**Comment by DheerajP** [comment] 2016-11-18 18:03
i cannot see any errors in console and am not using urchinTracker script?

Please see attached image.
![capture](https://cloud.githubusercontent.com/assets/6369306/20440764/45f6c996-adb9-11e6-9b6b-c2a8d076906b.JPG)

**Comment by ozdemirburak** [comment] 2016-12-11 20:38
I checked your page again, probably that urchinTracker is something related to Chrome, I'm not sure because I couldn't reproduce it on Firefox.

Anyway, you forgot to include the style file, probably that is what your issue is.

**Comment by ozdemirburak** [comment] 2017-01-11 13:31
Closing this, feel free to reopen if the problem still persists.

**Closed by ozdemirburak** 2017-01-11 13:31 UTC
