### ISSUE TITLE
Can't get it to work on my site, cannot read property data of undefined

### ISSUE THREAD

**Issue by bustapaladin** [ozdemirburak/jquery-floating-social-share#8] opened 2016-09-16 19:01 UTC
jquery.floating-social-share.min.js?ver=0.0.1:3 Uncaught TypeError: Cannot read property 'data' of undefined

jquery.floating-social-share.min.js?ver=0.0.1:3 Uncaught TypeError: Cannot read property 'share_count' of undefined

You can find my site at: http://madetoburst.com/

**Comment by ozdemirburak** [comment] 2016-09-17 12:16
Sorry but I couldn't reproduce the same error. However, seems like you have forgotten p tags in your script tag so that nothing works in the name of your jQuery scripts as the code below breaks the whole logic.

```html
<div  class="col-sm-12  single"><script>	
	jQuery( function($){</p>
<p>		$(document).on('click dblclick', '#fld_7908577_3', function( e ){
			$('#fld_7908577_3_btn').val( e.type ).trigger('change');
		});</p>
<p>	});
</script></p>```

**Comment by bustapaladin** [comment] 2016-09-17 15:51
On what page did you find that code? I'm having trouble locating it... I use Wordpress some and some small amount of plugins. I really have no idea what is breaking things.

**Comment by bustapaladin** [comment] 2016-09-21 14:24
Okay got it to work but that console error still shows up.

**Comment by ozdemirburak** [comment] 2016-09-21 23:45
Sorry for the late reply @bustapaladin,

The error itself is because of the reddit counters, when there is a share of none, then it throws that error, `Uncaught TypeError: Cannot read property 'data' of undefined`. 

Obviously, it's a bug, I'll fix that asap.

**Comment by ozdemirburak** [comment] 2016-09-28 13:19
@bustapaladin Closing this issue as hoping that it has resolved your issue. Please don't hesitate to reopen if you are still facing it.

**Closed by ozdemirburak** 2016-09-28 13:19 UTC
