### ISSUE TITLE
Pinterest sharing isn't working anymore

### ISSUE THREAD

**Issue by anarchoi** [ozdemirburak/jquery-floating-social-share#18] opened 2018-03-26 04:44 UTC
When clicking the share button it goes to a pinterest page saying "Whoops! We couldn’t find that page. How about these instead?"

**Comment by ozdemirburak** [comment] 2018-03-26 04:51
Thanks for reporting this, the issue is fixed now.

**Closed by ozdemirburak** 2018-03-26 04:51 UTC
